# Generated by Django 6.0.6 on 2026-08-17 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_attendance'),
    ]

    operations = [
        migrations.CreateModel(
            name='dept',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_name', models.CharField(max_length=100)),
                ('HOD_name', models.CharField(max_length=100)),
                ('supervisor_name', models.CharField(max_length=100)),
                ('code', models.IntegerField()),
            ],
        ),
    ]
